// build-react/src/compoments/navbar.jsx
import { useLocation, useNavigate } from "react-router-dom";
import styled from "styled-components";

const Bar = styled.div`
    display: grid;
    grid-template-columns: auto auto auto;
    margin-bottom: 10px;
`

export default function Navbar () {
    const location = useLocation();
    const navigate = useNavigate();
return (
    <Bar>
        <div className="button-container">
            <button disabled={location.pathname == "/random"} onClick={() => {navigate("/random")}}>Random quote</button>
        </div>
        <div className="button-container">
            <button disabled={location.pathname == "/popular"} onClick={() => {navigate("/popular")}}>Popular quote</button>
        </div>
        <div className="button-container">
            <button disabled={location.pathname == "/new"} onClick={() => {navigate("/new")}}>Write your own</button>
        </div>
    </Bar>

)}

// build-vue/src/components/NavBar.vue
<script setup lang="ts"></script>

<template>
  <div id="nav">
    <div class="button-container">
      <button 
        :disabled="$route.fullPath === '/random'" 
        @click="$router.push('/random')"
      >
        Random quote
      </button>
    </div>
    <div class="button-container">
      <button 
        :disabled="$route.fullPath === `/popular`" 
        @click="$router.push('/popular')"
      >
        Popular quote
      </button>
    </div>
    <div class="button-container">
      <button 
        :disabled="$route.fullPath === '/new'" 
        @click="$router.push('/new')"
      >
        Write your own
      </button>
    </div>
  </div>
</template>

<style scoped>
  #nav {
    display: grid;
    grid-template-columns: auto auto auto;
    margin-bottom: 10px;
  }
</style>
