// build-vue/src/pages/index.vue
<script setup lang="ts">
  import NavBar from "../components/NavBar.vue"
</script>

<template>
  <NavBar />
  <div id="placeholder">
    <p>Click one of the buttons above to get started!</p>
  </div>
</template>

<style scoped>
  #placeholder p {
    font-family: "Open Sans", sans-serif;
    font-size: 24px;
    font-weight: bold;
    text-align: center;
    margin: auto;
  }
</style>

// build-react/src/pages/index.jsx
import Navbar from "../compoments/navbar"
import styled from "styled-components";

const Placeholder = styled.p`
    font-family: "Tahoma", sans-serif;
    font-size: 24px;
    font-weight: bold;
    text-align: center;
    margin: 0px;
`

export default function index () {return (
    <div>
        <Navbar />
        <Placeholder>Click one of the buttons above to get started!</Placeholder>
    </div>
)}
