// build-vue/src/pages/new.vue
<script setup lang="ts">
  import { ref } from "vue"
  import { API_HOST, HOST } from "../utils/config"
  import type { apiErrorType, apiIdType } from "../utils/types"
  import NavBar from "../components/NavBar.vue"
  import Alert from "@nuxt/ui/runtime/components/Alert.vue"
  import Button from "@nuxt/ui/runtime/components/Button.vue"
  import Input from "@nuxt/ui/runtime/components/Input.vue"
  import Textarea from "@nuxt/ui/runtime/components/Textarea.vue"
  import { useClipboard } from "@vueuse/core"
  import HIShare from "../icons/HIShare.vue"
  import HIPencilSquare from "../icons/HIPencilSquare.vue"
  import HIDocumentDuplicate from "../icons/HIDocumentDuplicate.vue"
  import HIPaperAirplane from "../icons/HIPaperAirplane.vue"

  const quote = ref("")
  const name = ref("")
  const submitToggle = ref(false)
  const submitError = ref(false)
  const submitSuccess = ref(false)
  const errorMessage = ref("")
  const shareToggle = ref(false)
  const shareLink = ref("")

  const { copy } = useClipboard({legacy: true})
  const copyToggle = ref(false)

  const copyShareLink = async () => {
    await copy(shareLink.value)
    copyToggle.value = true
    setTimeout(() => {
      copyToggle.value = false
    }, 2000);
  }

  const submitQuote = async () => {
    submitError.value = false
    
    if (quote.value == "") {
      errorMessage.value = "Please enter a quote."
      submitError.value = true
    } else if (name.value == "") {
      errorMessage.value = "Please enter a name."
      submitError.value = true
    } else if (quote.value.length > 400) {
      errorMessage.value = "Quote should be less than 400 characters long."
      submitError.value = true
    } else if (name.value.length > 40) {
      errorMessage.value = "Name should be less than 40 characters long."
      submitError.value = true
    }

    if (submitError.value) {
      return
    }

    submitToggle.value = true
    const reqObj = {
      quote: quote.value,
      name: name.value
    }
    try {
      const res = await fetch(`${API_HOST}/new`,{
        method: 'POST', 
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(reqObj),
      })
      if (res.status === 400) {
        const resObj = await res.json() as apiErrorType
        errorMessage.value = resObj.message
        submitError.value = true
      } else if (res.ok) {
        const resObj = await res.json() as apiIdType
        shareLink.value = `${HOST}/id/${resObj.id}`
        submitSuccess.value = true
      } else {
        errorMessage.value = "Unable to submit quote."
        submitError.value = true
      }
  } catch {
      errorMessage.value = "Unable to submit quote."
      submitError.value = true
  } finally {
    if (submitError.value) {
      submitToggle.value = false
    }
  }
  }

  const reset = () => {
    quote.value = ""
    name.value = ""
    submitToggle.value = false
    submitSuccess.value = false
    shareToggle.value = false
  }
</script>

<template>
  <div>
    <NavBar />
    
    <div class="pb-1">
      <Alert
        v-if="submitError"
        color="error"
        variant="subtle"
        :ui="{title: 'text-base font-bold', description: 'text-base opacity-100'}"
        title="Error"
        :description="errorMessage"
      />
      <Alert 
        v-else-if="submitSuccess"
        color="success"
        variant="subtle"
        :ui="{title: 'pb-1 text-base font-bold', description: 'w-full'}"
        title="Quote submitted!"
      >
        <template #description>
          <div class="sm:grid sm:grid-cols-2">
            <div class="pb-1 sm:pb-0 sm:pr-0.5">
              <Button 
                color="success"
                class="block w-full text-center text-base font-bold"
                :disabled="shareToggle"
                @click="() => {shareToggle = true}"
              >
                <template #leading><HIShare /></template>
                Share this quote
              </Button>
            </div>
            <div class="pb-1 sm:pb-0 sm:pl-0.5">
              <Button 
                color="success"
                class="block w-full text-center text-base font-bold"
                @click="reset"
              >
                <template #leading><HIPencilSquare /></template>
                Write another quote
              </Button>
            </div>
          </div>

          <div v-if="shareToggle" class="pt-1 pb-2">
            <p class="pt-1 text-base font-normal">Copy this link to share:</p>
            <div class="grid grid-cols-[1fr_auto] pt-1">
              <div>
                <Input 
                  :model-value="shareLink" 
                  disabled 
                  :ui="{root: 'w-full', base: 'text-base disabled:cursor-text'}"
                />
              </div>
              <div class="pl-1">
                <Button 
                  :disabled="copyToggle"
                  color="success"
                  class="text-base font-bold"
                  @click="copyShareLink"
                >
                  <template #leading><HIDocumentDuplicate /></template>
                  {{copyToggle ? 'Copied!' : 'Copy'}}
                </Button>
              </div>
            </div>
          </div>
        </template>
      </Alert>
      
      <Alert 
        v-else
        color="warning"
        variant="subtle"
        :ui="{title: 'text-base font-bold', description: 'text-base font-normal opacity-100'}"
        title="Warning"
        description="Anything you submit here can be seen by anyone on the internet. Do not submit any personal or sensitive information."
      />
    </div>

    <form @submit.prevent="submitQuote">
      <label for="quote" class="block font-bold py-1">Your Quote</label>
      <Textarea
        id="quote"
        v-model="quote"
        :disabled="submitToggle"
        autocomplete="off"
        :rows="4"
        :ui="{root: 'w-full', base: 'text-base'}"
      />
      <p :class="`text-xs text-right transition-colors ${quote.length > 400 ? 'text-red-500 dark:text-red-400' : ''}`">
        {{quote.length}}/400
      </p>

      <label for="name" class="block font-bold py-1">Your Name</label>
      <Input
        id="name"
        v-model="name"
        :disabled="submitToggle"
        autocomplete="off"
        :ui="{root: 'w-full', base: 'text-base'}"
      />
      <p :class="`text-xs text-right transition-colors ${name.length > 40 ? 'text-red-500 dark:text-red-400' : ''}`">
        {{name.length}}/40
      </p>

      <div class="pt-1">
        <Button 
          type="submit"
          :disabled="submitToggle"
          class="block w-full text-base text-center font-bold"
        >
          <template #leading><HIPaperAirplane /></template>
          Submit Quote
        </Button>
      </div>
    </form>
  </div>
</template>

// build-react/src/pages/new.tsx
import { FormEvent, useState } from "react"
import { API_HOST, HOST } from "../utils/config"
import NavBar from "../components/NavBar"
import { Alert, Button, Input, Textarea } from "@heroui/react"
import { useCopyToClipboard } from "@uidotdev/usehooks"
import HIShare from "../icons/HIShare"
import HIPencilSquare from "../icons/HIPencilSquare"
import HIDocumentDuplicate from "../icons/HIDocumentDuplicate"
import HIPaperAirplane from "../icons/HIPaperAirplane"

export default function New_ () {
  const [quote, updateQuote] = useState("")
  const [name, updateName] = useState("")
  const [submitToggle, updateSubmitToggle] = useState(false)
  const [submitError, updateSubmitError] = useState(false)
  const [submitSuccess, updateSubmitSuccess] = useState(false)
  const [errorMessage, updateErrorMessage] = useState("")
  const [shareToggle, updateShareToggle] = useState(false)
  const [shareLink, updateShareLink] = useState("")

  const copy = useCopyToClipboard()[1]
  const [copyToggle, copyToggleUpdate] = useState(false)

  const copyShareLink = async () => {
    await copy(shareLink)
    copyToggleUpdate(true)
    setTimeout(() => {
      copyToggleUpdate(false)
    }, 2000);
  }


  const submitQuote = async (event: FormEvent<HTMLFormElement>) => {
    console.log("Submit")
    event.preventDefault()
    updateSubmitError(false)
    let submitErrorVar = false
    
    if (quote === "") {
      updateErrorMessage("Please enter a quote.")
      updateSubmitError(true)
      submitErrorVar = true
    } else if (name === "") {
      updateErrorMessage("Please enter a name.")
      updateSubmitError(true)
      submitErrorVar = true
    } else if (quote.length > 400) {
      updateErrorMessage("Quote should be less than 400 characters long.")
      updateSubmitError(true)
      submitErrorVar = true
    } else if (name.length > 40) {
      updateErrorMessage("Name should be less than 40 characters long.")
      updateSubmitError(true)
      submitErrorVar = true
    }
    if (submitErrorVar) {
      return
    }

    updateSubmitToggle(true)
    const reqObj = {
      quote: quote,
      name: name
    }
    let resObj
    try {
      const res = await fetch(`${API_HOST}/new`,{
        method: 'POST', 
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(reqObj),
      })
      if (res.status === 400) {
        resObj = await res.json()
        updateErrorMessage(resObj.errorMessage)
        updateSubmitError(true)
        submitErrorVar = true
      } else if (res.ok) {
        resObj = await res.json()
        updateShareLink(`${HOST}/id/${resObj.id}`)
        updateSubmitSuccess(true)
      } else {
        updateErrorMessage("Unable to submit quote.")
        updateSubmitError(true)
        submitErrorVar = true
      }
    } catch {
      updateErrorMessage("Unable to submit quote.")
      updateSubmitError(true)
      submitErrorVar = true
    } finally {
      if (submitErrorVar) {
        updateSubmitToggle(false)
      }
    }
  }

  const reset = () => {
    updateQuote("")
    updateName("")
    updateSubmitToggle(false)
    updateSubmitSuccess(false)
    updateShareToggle(false)
  }

  return (
    <div>
      <NavBar />
      <div className="pb-1">
        {submitError ? (
          <Alert
            hideIcon
            color="danger"
            variant="faded"
            classNames={{mainWrapper: 'ms-0', title: 'text-base font-bold', description: 'text-base'}}
            title="Error"
            description={errorMessage}
          />
        ) : submitSuccess ? (
          <Alert 
            hideIcon
            color="success"
            variant="faded"
            classNames={{mainWrapper: 'ms-0', title: 'pb-2 text-base font-bold', description: 'w-full'}}
            title="Quote submitted!"
            description={<>
              <div className="sm:grid sm:grid-cols-2">
                <div className="pb-1 sm:pb-0 sm:pr-0.5">
                  <Button
                    color="success"
                    className="w-full text-base font-bold"
                    isDisabled={shareToggle}
                    onPress={() => {updateShareToggle(true)}}
                    startContent={<HIShare />}
                  >
                    Share this quote
                  </Button>
                </div>
                <div className="pb-1 sm:pb-0 sm:pl-0.5">
                  <Button
                    color="success"
                    className="w-full text-base font-bold"
                    onPress={reset}
                    startContent={<HIPencilSquare />}
                  >
                    Write another quote
                  </Button>
                </div>
              </div>
              {shareToggle && (
                <div className="pt-1 pb-2">
                  <p className="pt-1 text-base font-normal">Copy this link to share:</p>
                  <div className="grid grid-cols-[1fr_auto] pt-1">
                    <div>
                      <Input 
                        value={shareLink}
                        isDisabled
                        variant="bordered"
                        classNames={{base: 'w-full', input: 'text-base cursor-text pointer-events-auto'}}
                      />
                    </div>
                    <div className="pl-1">
                      <Button 
                        isDisabled={copyToggle}
                        color="success"
                        className="text-base font-bold"
                        onPress={copyShareLink}
                        startContent={<HIDocumentDuplicate />}
                      >
                        {copyToggle ? 'Copied!' : 'Copy'}
                      </Button>
                    </div>
                  </div>
                </div>
              )}
            </>}
          />
        ) : (
          <Alert
            hideIcon
            color="warning"
            variant="faded"
            classNames={{mainWrapper: 'ms-0', title: 'text-base font-bold', description: 'text-base'}}
            title="Warning"
            description="Anything you submit here can be seen by anyone on the internet. Do not submit any personal or sensitive information."
          />
        )}
      </div>
      
      <form onSubmit={submitQuote}>
        <label htmlFor="quote" className="block font-bold py-1">Your Quote</label>
        <Textarea 
          id="quote"
          value={quote}
          onValueChange={updateQuote}
          isDisabled={submitToggle}
          autoComplete="off"
          rows={4}
          variant="bordered"
          classNames={{base: 'w-full', input: 'text-base'}}
        />
        <p className={`text-xs text-right transition-colors ${quote.length > 400 ? 'text-red-500 dark:text-red-400' : ''}`}>
          {quote.length}/400
        </p>
        
        <label htmlFor="name" className="block font-bold py-1">Your Name</label>
        <Input 
          id="name"
          value={name}
          onValueChange={updateName}
          isDisabled={submitToggle}
          autoComplete="off"
          variant="bordered"
          classNames={{base: 'w-full', input: 'text-base'}}
        />
        <p className={`text-xs text-right transition-colors ${name.length > 40 ? 'text-red-500 dark:text-red-400' : ''}`}>
          {name.length}/400
        </p>
        
        <div className="pt-1">
          <Button
            type="submit"
            isDisabled={submitToggle}
            color="primary"
            className="w-full text-base font-bold"
            startContent={<HIPaperAirplane />}
          >
            Submit Quote
          </Button>
        </div>
      </form>
    </div>
  )
}
