// build-react/src/App.tsx
import { useEffect, useState } from 'react'
import './style.css'
import styled from 'styled-components'
import { API_HOST } from './utils/config'
import { RouterView } from './router'

const Header = styled.h1`
  font-family: "Open Sans", sans-serif;
  font-size: 32px;
  font-weight: bold;
  text-align: center;
  line-height: 16px;
`
const BuildInfo = styled.p`
  font-family: "Open Sans", sans-serif;
  text-align: center;
`
const ContentArea = styled.div`
  width: 360px;
  margin: 0 auto;
`
const NoApi = styled.div`
  width: 340px;
  padding: 10px;
  align-items: center;
  background-color: #ffaaaa;
  margin: auto;
  font-family: "Open Sans", sans-serif;
  text-align: center;
`

function App() {
  const [apiOnline, apiOnlineUpdate] = useState(true)

  async function doHandshake () {
    let handshake;
    try {
      handshake = await fetch(`${API_HOST}/handshake`)
      console.log(handshake.ok)
      if (handshake.ok) {
        apiOnlineUpdate(true)
      } else {
        apiOnlineUpdate(false)
      }
    } catch {
      apiOnlineUpdate(false)
    }
  }

  useEffect(() => {doHandshake()}, [])

  return (
    <div>
      <Header>Quotemaster</Header>
      <BuildInfo>React build v0.2.0</BuildInfo>
      <BuildInfo>
        <a 
          href="https://github.com/cockatoo-dev/quotemaster/"
          rel="noreferrer noopener"
        >
          View source on Github
        </a>
      </BuildInfo>
      
      {apiOnline ? (
        <ContentArea>
          <RouterView />
        </ContentArea>
      ) : (
        <NoApi>
          <p>Unable to reach API server.</p>
          <div className="button-container">
            <button onClick={() => {doHandshake()}}>Retry</button>
          </div>
        </NoApi>
      )}
    </div>
  )
}

export default App

// build-vue/src/App.vue
<script setup lang="ts">
  import { ref, onMounted } from "vue"
  import { RouterView } from 'vue-router'
  import { API_HOST } from "./utils/config"

  const apiOnline = ref(true)

  async function doHandshake () {
    try {
      const handshake = await fetch(`${API_HOST}/handshake`)
      if (handshake.ok) {
        apiOnline.value = true
      } else {
        apiOnline.value = false
      }
    } catch {
      apiOnline.value = false
    }
  }
  
  onMounted(doHandshake)
</script>

<template>
  <div id="header">
    <h1>Quotemaster</h1>
    <p>Vue build v0.5.0</p>
    <p>
      <a 
        href="https://github.com/cockatoo-dev/quotemaster/"
        rel="noreferrer noopener"
      >
        View source on Github
      </a>
    </p>
  </div>
  <div id="no-api" v-if="!apiOnline">
    <p>Unable to reach API server.</p>
    <div class="button-container">
      <button @click="doHandshake()">Retry</button>
    </div>
  </div>
  <div id="content" v-else>
    <RouterView />
  </div>
</template>

<style scoped>
  .button-container {
    text-align: center;
  }
  #header h1 {
    font-family: "Open Sans", sans-serif;
    font-weight: bold;
    font-size: 32px;
    text-align: center;
    line-height: 16px;
  }
  #header p {
    font-family: "Open Sans", sans-serif;
    text-align: center;
  }
  #no-api {
    width: 340px;
    margin: auto;
    padding: 10px;
    font-family: "Open Sans", sans-serif;
    text-align: center;
    background-color: #ffaaaa;
  }
  #content {
    width: 360px;
    margin: 0 auto;
  }
  button {
    margin: auto;
  }
</style>
