// build-react/src/pages/id.jsx
import React from "react";
import { useParams } from "react-router-dom";
import styled from "styled-components";

import Navbar from "../compoments/navbar.jsx";
import QuoteRenderer from "../compoments/quoteRenderer.jsx";

import * as config from "../config.js";

const ErrorLayover = styled.div`
    font-family: "Tahoma", sans-serif;
    text-align: center;
    background-color: #ffaaaa;
    margin: auto;
    padding: 10px;
`

export default function Id () {
    const ID = useParams().id;
    const [QUOTE, updateQuote] = React.useState(null);
    const [error, updateError] = React.useState(false);
    const [errorMessage, updateErrorMessage] = React.useState("Unable to load quote.");
    
    async function getQuote () {
        let res, errorObj;
        try {
            res = await fetch(`${config.API_HOST}/quotemaster/id/${ID}`);
            if (!res.ok) {
                updateError(true);
                if (res.status == 400) {
                    errorObj = await res.json();
                    updateErrorMessage(errorObj.errorMessage);
                } else {
                    updateErrorMessage("Unable to load quote.");
                }
            } else {
                updateQuote(await res.json());
            }
        } catch {
            updateError(true);
            updateErrorMessage("Unable to load quote.");
        }
    }

    React.useEffect(() => {getQuote()},[]);
    
    return (
        <div>
            <Navbar />
            {error ? (
                <ErrorLayover>
                    <p>{errorMessage}</p>
                    <button onClick={getQuote}>Retry</button>
                </ErrorLayover>
            ) : (
                <div>
                    <QuoteRenderer quote={QUOTE} />
                </div>
            )}
        </div>
    )
}

// build-vue/src/views/id.vue
<script setup>
    import { ref, onMounted } from "vue";
    import { useRoute } from "vue-router";

    import * as config from "../config.js";
    import quoteRenderer from "../components/quoteRenderer.vue";

    const ROUTE = useRoute();
    const ID = ROUTE.params.id;
    const QUOTE = ref(null);
    let error = ref(false);
    let errorMessage = ref("Unable to load quote.");


    async function getQuote () {
        let res, errorObj;
        try {
            res = await fetch(`${config.API_HOST}/quotemaster/id/${ID}`);
            if (!res.ok) {
                error.value = true;
                if (res.status == 400) {
                    errorObj = await res.json();
                    errorMessage.value = errorObj.errorMessage;
                }
            } else {
                QUOTE.value = await res.json();
            }
        } catch {
            error.value = true;
        }
    }

    onMounted(getQuote);
</script>

<template>
    <div id="error-layover" v-if="error">
        <p>{{errorMessage}}</p>
        <div class="button-container">
            <button @click="getQuote">Retry</button>
        </div>
    </div>
    <div id="quote-display" v-else>
        <quoteRenderer :quote="QUOTE" />
    </div>
</template>

<style scoped>
    p {
        font-family: "Tahoma", sans-serif;
        font-size: 24px;
        font-weight: bold;
        padding: 10px;
        text-align: center;
    }
    .button-container {
        text-align: center;
    }
    #error-layover {
        background-color: #ffaaaa;
        margin: auto;
        padding:10px;
    }
</style>
