// build-react/src/pages/random.jsx
import React from "react";
import styled from "styled-components";

import Navbar from "../compoments/navbar"
import QuoteRenderer from "../compoments/quoteRenderer.jsx";

import * as config from "../config.js";

const ErrorLayover = styled.div`
    font-family: "Tahoma", sans-serif;
    text-align: center;
    background-color: #ffaaaa;
    margin: auto;
    padding: 10px;
`
const ReloadButton = styled.button`
    margin-top: 10px;
`


export default function Random () {
    const [QUOTE, updateQuote] = React.useState(null);
    const [error, updateError] = React.useState(false);
    
    async function getQuote () {
        updateQuote(null);
        updateError(false);

        let res;
        try {
            res = await fetch(`${config.API_HOST}/quotemaster/random`);
            if (!res.ok) {
                updateError(true);
            } else {
                updateQuote(await res.json());
            }
        } catch {
            updateError(true);
        }
    }

    React.useEffect(() => {getQuote()}, []);

    return (
        <div>
            <Navbar />
            {error ? (
                <ErrorLayover>
                    <p>Unable to load quote.</p>
                    <button onClick={getQuote}>Retry</button>
                </ErrorLayover>
            ) : (
                <div>
                    <QuoteRenderer quote={QUOTE} />
                    <div className="button-container">
                        <ReloadButton onClick={getQuote}>Get another quote</ReloadButton>
                    </div>
                </div>
            )}
        </div>
    )
}

// build-vue/src/views/random.vue
<script setup>
    import { ref, onMounted } from "vue";

    import * as config from "../config.js";
    import quoteRenderer from "../components/quoteRenderer.vue"

    const QUOTE = ref(null);
    const error = ref(false);

    async function getQuote () {
        QUOTE.value = null;
        error.value = false;

        let res;
        try {
            res = await fetch(`${config.API_HOST}/quotemaster/random`);
            if (!res.ok) {
                error.value = true;
            } else {
                QUOTE.value = await res.json();
            }
        } catch {
            error.value = true;
        }
    }

    onMounted(getQuote);

</script>

<template>
    <div id="error-layover" v-if="error">
        <p>Unable to load quote.</p>
        <div class="button-container">
            <button @click="getQuote">Retry</button>
        </div>
    </div>
    <div v-else>
        <quoteRenderer :quote="QUOTE" />
        <div id="reload-button" class="button-container">
            <button @click="getQuote">Get another quote!</button>
        </div>
    </div>
</template>

<style scoped>
    p {
        font-family: "Tahoma", sans-serif;
        font-size: 24px;
        font-weight: bold;
        padding: 10px;
        text-align: center;
    }
    .button-container {
        text-align: center;
    }
    #error-layover {
        background-color: #ffaaaa;
        margin: auto;
        padding:10px;
    }
    #reload-button {
        padding-top: 10px;
    }

</style>
