// build-react/src/pages/id.tsx
import { useParams } from "react-router"
import styled from "styled-components"
import { useCallback, useEffect, useState } from "react"
import NavBar from "../components/NavBar.js"
import QuoteRenderer from "../components/QuoteRenderer"
import { apiErrorType, apiQuoteType } from "../utils/types"
import { API_HOST } from "../utils/config"

const ErrorLayover = styled.div`
  font-family: "Open Sans", sans-serif;
  text-align: center;
  background-color: #ffaaaa;
  margin: auto;
  padding: 10px;
`

export default function Id () {
  const id = useParams().id
  const [quote, updateQuote] = useState<apiQuoteType | null>(null)
  const [error, updateError] = useState(false)
  const [errorMessage, updateErrorMessage] = useState("Unable to load quote.")
  
  const getQuote = useCallback(async () => {
    try {
      const res = await fetch(`${API_HOST}/id?id=${id}`)
      if (!res.ok) {
        updateError(true)
        if (res.status === 400) {
          const errorObj = await res.json() as apiErrorType
          updateErrorMessage(errorObj.message)
        } else {
          updateErrorMessage("Unable to load quote.")
        }
      } else {
        updateQuote(await res.json() as apiQuoteType)
      }
    } catch {
      updateError(true)
      updateErrorMessage("Unable to load quote.")
    }
  }, [id])

  useEffect(() => {getQuote()},[getQuote])
  
  return (
    <div>
      <NavBar />
      {error ? (
        <ErrorLayover>
          <p>{errorMessage}</p>
          <button onClick={getQuote}>Retry</button>
        </ErrorLayover>
      ) : (
        <div>
          <QuoteRenderer quote={quote} />
        </div>
      )}
    </div>
  )
}

// build-vue/src/pages/id.vue
<script setup lang="ts">
  import { ref, onMounted } from "vue"
  import { useRoute } from "vue-router"
  import NavBar from "../components/NavBar.vue"
  import { API_HOST } from "../utils/config"
  import QuoteRenderer from "../components/QuoteRenderer.vue"
  import type { apiErrorType, apiQuoteType } from "../utils/types"

  const route = useRoute()
  const id = route.params.id
  const quote = ref<apiQuoteType | null>(null)
  const error = ref(false)
  const errorMessage = ref("Unable to load quote.")


  const getQuote = async () => {
    try {
      const res = await fetch(`${API_HOST}/id?id=${id}`)
      if (!res.ok) {
        error.value = true
        if (res.status === 400) {
          const errorObj = await res.json() as apiErrorType
          errorMessage.value = errorObj.message
        } else {
          errorMessage.value = "Unable to load quote."
        }
      } else {
        quote.value = await res.json() as apiQuoteType
      }
    } catch {
      error.value = true
      errorMessage.value = "Unable to load quote."
    }
  }

  onMounted(getQuote)
</script>

<template>
  <NavBar />
  <div id="error-layover" v-if="error">
    <p>{{errorMessage}}</p>
    <div class="button-container">
      <button @click="getQuote">Retry</button>
    </div>
  </div>
  <div id="quote-display" v-else>
    <QuoteRenderer :quote="quote" />
  </div>
</template>

<style scoped>
  .button-container {
    text-align: center;
  }
  #error-layover {
    background-color: #ffaaaa;
    margin: auto;
    padding:10px;
    font-family: "Open Sans", sans-serif;
    text-align: center;
  }
</style>
