// build-react/src/pages/new.jsx
import React from "react";
import styled from "styled-components";

import Navbar from "../compoments/navbar"

import * as config from "../config.js";

const BoxText = styled.p`
    font-family: "Tahoma", sans-serif;
    font-weight: bold;
    margin: 0px;
`
const ErrorBox = styled.div`
    background-color: #ffaaaa;
    padding: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
`
const SuccessBox = styled.div`
    background-color: #aaffaa;
    padding: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
`
const SubmitActions = styled.div`
    display:grid;
    grid-template-columns: auto auto;
    padding-top: 10px;
`

const ShareHeader = styled.p`
    font-family: "Tahoma", sans-serif;
    margin-bottom: 0px;
`
const ShareLinkBox = styled.input`
    width: 354px;
    padding:2px;
    border-width:1px;
    font-family: "Tahoma", sans-serif;
    font-size: 16px;
`
const WarningBox = styled.div`
    background-color: #ffffaa;
    padding: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
`
const WarningTitle = styled.h2`
    font-family: "Tahoma", sans-serif;
    font-size: 16px;
    font-weight: bold;
    margin-top:0px;
    margin-bottom: 5px;
`
const WarningText = styled.p`
    font-family: "Tahoma", sans-serif;
    margin: 0px;
`
const FormLabel = styled.label`
    font-family: "Tahoma", sans-serif;
    font-weight: bold;
`
const QuoteTextarea = styled.textarea`
    width: 354px;
    padding:2px;
    border-width:1px;
    font-family: "Tahoma", sans-serif;
    font-size: 16px;
`
const NameInput = styled.input`
    width: 354px;
    padding:2px;
    border-width:1px;
    font-family: "Tahoma", sans-serif;
    font-size: 16px;
`
const CharLimit = styled.p`
    font-family: "Tahoma", sans-serif;
    text-align: right;
    margin-top: 0px;
`
export default function New_ () {
    const [quote, updateQuote] = React.useState("");
    const [name, updateName] = React.useState("");
    const [submitToggle, updateSubmitToggle] = React.useState(false);
    const [submitError, updateSubmitError] = React.useState(false);
    const [submitSuccess, updateSubmitSuccess] = React.useState(false);
    const [errorMessage, updateErrorMessage] = React.useState("");
    const [shareToggle, updateShareToggle] = React.useState(false);
    const [shareLink, updateShareLink] = React.useState("");

    let messageBox;

    async function submitQuote () {
        updateSubmitToggle(true);
        updateSubmitError(false);
        
        if (quote == "") {
            updateErrorMessage("Please enter a quote.");
            updateSubmitError(true);
        } else if (name.value == "") {
            updateErrorMessage("Please enter a name.");
            updateSubmitError(true);
        } else if (quote.value.length > 400) {
            updateErrorMessage("Quote should be less than 400 characters long.");
            updateSubmitError(true);
        } else if (name.value.length > 40) {
            updateErrorMessage("Name should be less than 40 characters long.");
            updateSubmitError(true);
        }
        if (submitError) {
            updateSubmitToggle(false);
            return;
        }

        let reqObj = {
            quote: quote,
            name: name
        }
        let resObj;
        try {
            let res = await fetch(`${config.API_HOST}/quotemaster/new`,{
                method: 'POST', 
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(reqObj),
            });
            if (res.status == 400) {
                resObj = await res.json();
                updateErrorMessage(resObj.errorMessage);
                updateSubmitError(true);
            } else if (res.ok) {
                resObj = await res.json();
                updateShareLink(`${config.HOST}/id/${resObj.id}`);
                updateSubmitSuccess(true);
            } else {
                updateErrorMessage("Unable to submit quote.");
                updateSubmitError(true);
            }
        } catch {
            updateErrorMessage("Unable to submit quote.");
            updateSubmitError(true);
        }
    }

    function reset () {
        updateQuote("");
        updateName("");
        updateSubmitToggle(false);
        updateSubmitSuccess(false);
        updateShareToggle(false);
    }
    
    if (submitError) {
        messageBox = (
            <ErrorBox>
                <BoxText>{errorMessage}</BoxText>
            </ErrorBox>
        )
    } else if (submitSuccess) {
        messageBox = (
            <SuccessBox>
                <BoxText>Quote submitted!</BoxText>
                <SubmitActions>
                    <div className="button-container">
                        <button>Share this quote</button>
                    </div>
                    <div className="button-container">
                        <button>Write another quote</button>
                    </div>
                </SubmitActions>
                {shareToggle ? (
                    <div>
                        <ShareHeader>Copy this link to share:</ShareHeader>
                        <ShareLinkBox type="text" value={shareLink} disabled></ShareLinkBox> 
                    </div>
                ) : <div></div>}
            </SuccessBox>
        )
    } else {
        messageBox = (
            <WarningBox>
                <WarningTitle>Warning</WarningTitle>
                <WarningText>Anything you submit here is publicly viewable. Do not submit any personal or sensitive information.</WarningText>
            </WarningBox>
        )
    }

    return (
        <div>
            <Navbar />
            {messageBox}
            <form>
                <FormLabel for="quote">Your quote</FormLabel>
                <QuoteTextarea id="quote" rows="4"></QuoteTextarea>
                <CharLimit>/400</CharLimit>
                <FormLabel for="name">Your name</FormLabel>
                <NameInput id="name"></NameInput>
                <CharLimit>/40</CharLimit>
                <button type="submit">Submit quote</button>
            </form>
        </div>
    )
}

// build-vue/src/pages/new.vue
<script setup lang="ts">
  import { ref } from "vue"
  import { API_HOST, HOST } from "../utils/config"
  import type { apiErrorType, apiIdType } from "../utils/types"
import NavBar from "../components/NavBar.vue"

  const quote = ref("")
  const name = ref("")
  const submitToggle = ref(false)
  const submitError = ref(false)
  const submitSuccess = ref(false)
  const errorMessage = ref("")
  const shareToggle = ref(false)
  const shareLink = ref("")

  const submitQuote = async () => {
    submitError.value = false
    
    if (quote.value == "") {
      errorMessage.value = "Please enter a quote."
      submitError.value = true
    } else if (name.value == "") {
      errorMessage.value = "Please enter a name."
      submitError.value = true
    } else if (quote.value.length > 400) {
      errorMessage.value = "Quote should be less than 400 characters long."
      submitError.value = true
    } else if (name.value.length > 40) {
      errorMessage.value = "Name should be less than 40 characters long."
      submitError.value = true
    }

    if (submitError.value) {
      return
    }

    submitToggle.value = true
    const reqObj = {
      quote: quote.value,
      name: name.value
    }
    try {
      const res = await fetch(`${API_HOST}/new`,{
        method: 'POST', 
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(reqObj),
      })
      if (res.status === 400) {
        const resObj = await res.json() as apiErrorType
        errorMessage.value = resObj.message
        submitError.value = true
      } else if (res.ok) {
        const resObj = await res.json() as apiIdType
        shareLink.value = `${HOST}/id/${resObj.id}`
        submitSuccess.value = true
      } else {
        errorMessage.value = "Unable to submit quote."
        submitError.value = true
      }
  } catch {
      errorMessage.value = "Unable to submit quote."
      submitError.value = true
  } finally {
    if (submitError.value) {
      submitToggle.value = false
    }
  }
  }

  const reset = () => {
    quote.value = ""
    name.value = ""
    submitToggle.value = false
    submitSuccess.value = false
    shareToggle.value = false
  }
</script>

<template>
  <NavBar />
  
  <div id="submit-error" v-if="submitError">
    <p>{{errorMessage}}</p>
  </div>
  <div id="submit-success" v-else-if="submitSuccess">
    <p>Quote submitted!</p>

    <div id="submit-actions">
      <div>
        <button 
          @click="() => {shareToggle = true}" 
          :disabled="shareToggle"
        >
          Share this quote
        </button>
      </div>
      <div>
        <button @click="reset">Write another quote</button>
      </div>
    </div>

    <div id="share-link" v-if="shareToggle">
      <p>Copy this link to share:</p>
      <input type="text" :value="shareLink" disabled>
    </div>
  </div>
  <div id="warning" v-else>
    <h2>Warning</h2>
    <p>
      Anything you submit here is publicly viewable. Do not submit any personal or sensitive information.
    </p>
  </div>

  <form @submit.prevent="submitQuote">
    <label for="quote">Your quote</label>
    <textarea id="quote" rows="4" v-model="quote" :disabled="submitToggle" />
    <p class="char-limit" :class="{warn:quote.length > 400}">{{quote.length}}/400</p>

    <label for="name">Your name</label>
    <input type="text" id="name" v-model="name" :disabled="submitToggle">
    <p class="char-limit" :class="{warn:name.length > 40}">{{name.length}}/40</p>

    <button type="submit" :disabled="submitToggle">Submit quote</button>
  </form>
</template>

<style scoped>
  input, textarea {
    font-family: "Open Sans", sans-serif;
  }
  #submit-error {
    font-family: "Open Sans", sans-serif;  
    background-color: #ffaaaa;
    padding: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
  }
  #submit-error p {
    font-weight: bold;
    margin: 0px;
  }
  #submit-success {
    background-color: #aaffaa;
    padding: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
  }
  #submit-success p {
    font-weight: bold;
    margin: 0px;
  }
  #submit-actions {
    display:grid;
    grid-template-columns: auto auto;
    padding-top: 10px;
  }
  #submit-actions div {
    margin: auto;
  }
  #share-link {
    align-items: center;
    margin-top: 10px;
  }
  #share-link p {
    font-weight: normal;
  }
  #share-link input {
    width: 334px;
    padding:2px;
    border-width:1px;
    font-family: "Open Sans", sans-serif;
    font-size: 16px;
  }
  #warning {
    background-color: #ffffaa;
    padding: 10px;
    margin-bottom: 10px;
  }
  #warning h2 {
    font-size: 16px;
    font-weight: bold;
    margin-top:0px;
    margin-bottom: 5px;
  }
  #warning p {
    margin:0px;
  }
  #quote {
    width: 354px;
    padding:2px;
    border-width:1px;
    font-size: 16px;
  }
  #name {
    width: 354px;
    padding:2px;
    border-width:1px;
    font-size: 16px;
  }
  label {
    font-weight: bold;
  }
  .char-limit {
    margin-top: 0px;
    text-align: right;
  }
  .warn {
    color:#ff0000;
  }
</style>
