// build-react/src/pages/popular.jsx
import React from "react";
import styled from "styled-components";

import Navbar from "../compoments/navbar"
import QuoteRenderer from "../compoments/quoteRenderer.jsx";

import * as config from "../config.js";

const ErrorLayover = styled.div`
    font-family: "Tahoma", sans-serif;
    text-align: center;
    background-color: #ffaaaa;
    margin: auto;
    padding: 10px;
`
const ReloadButton = styled.button`
    margin-top: 10px;
`


export default function Popular () {
    const [QUOTE, updateQuote] = React.useState(null);
    const [error, updateError] = React.useState(false);
    
    async function getQuote () {
        updateQuote(null);
        updateError(false);

        let res;
        try {
            res = await fetch(`${config.API_HOST}/quotemaster/popular`);
            if (!res.ok) {
                updateError(true);
            } else {
                updateQuote(await res.json());
            }
        } catch {
            updateError(true);
        }
    }

    React.useEffect(() => {getQuote()}, []);

    return (
        <div>
            <Navbar />
            {error ? (
                <ErrorLayover>
                    <p>Unable to load quote.</p>
                    <button onClick={getQuote}>Retry</button>
                </ErrorLayover>
            ) : (
                <div>
                    <QuoteRenderer quote={QUOTE} />
                    <div className="button-container">
                        <ReloadButton onClick={getQuote}>Get another quote</ReloadButton>
                    </div>
                </div>
            )}
        </div>
    )
}

// build-vue/src/pages/popular.vue
<script setup lang="ts">
  import { ref, onMounted } from "vue"
  import { API_HOST } from "../utils/config"
  import type { apiQuoteType } from "../utils/types"
  import NavBar from "../components/NavBar.vue"
  import QuoteRenderer from "../components/QuoteRenderer.vue"

  const quote = ref<apiQuoteType | null>(null)
  const error = ref(false)

  const getQuote = async () => {
    quote.value = null
    error.value = false

    try {
      const res = await fetch(`${API_HOST}/popular`)
      if (!res.ok) {
        error.value = true
      } else {
        quote.value = await res.json() as apiQuoteType
      }
    } catch {
      error.value = true
    }
  }

  onMounted(getQuote)
</script>

<template>
  <NavBar />
  <div id="error-layover" v-if="error">
    <p>Unable to load quote.</p>
    <div class="button-container">
      <button @click="getQuote">Retry</button>
    </div>
  </div>
  <div id="quote-display" v-else>
    <QuoteRenderer :quote="quote" />
    <div id="reload-button" class="button-container">
      <button @click="getQuote">Get another quote</button>
    </div>
  </div>
</template>

<style scoped>
  #error-layover {
    background-color: #ffaaaa;
    margin: auto;
    padding: 10px;
    font-family: 'Open Sans', sans-serif;
    text-align: center;
  }
  #reload-button {
    padding-top: 10px;
  }
</style>
