// build-vue/src/components/NavBar.vue
<script setup lang="ts">
  import Button from '@nuxt/ui/runtime/components/Button.vue'
  import HILightBulb from '../icons/HILightBulb.vue';
  import HIStar from '../icons/HIStar.vue';
  import HIPencilSquare from '../icons/HIPencilSquare.vue';
</script>

<template>
  <div class="pb-2">
    <div class="sm:grid sm:grid-cols-3 gap-2 border-y border-y-green-400 dark:border-y-green-500">
      <div class="py-1">
        <Button 
          color="primary"
          variant="ghost"
          class="w-full justify-center text-base font-normal"
          to="/random"
        >
          <template #leading><HILightBulb /></template>
          Random Quote
        </Button>
      </div>
      <div class="py-1">
        <Button 
          color="primary"
          variant="ghost"
          class="w-full justify-center text-base font-normal"
          to="/popular"
        >
          <template #leading><HIStar /></template>
          <div>Popular Quote</div>
        </Button>
      </div>
      <div class="py-1">
        <Button 
          color="primary"
          variant="ghost"
          class="w-full justify-center text-base font-normal"
          to="/new"
        >
          <template #leading><HIPencilSquare /></template>
          Write Your Own
        </Button>
      </div>
    </div>
  </div>
</template>

// build-react/src/components/NavBar.tsx
import { Button } from "@heroui/react"
import { Link } from "react-router"
import HILightBulb from "../icons/HILightBulb"
import HIStar from "../icons/HIStar"
import HIPencilSquare from "../icons/HIPencilSquare"

export default function NavBar () {
return (
  <div className="pb-2">
    <div className="sm:grid sm:grid-cols-3 gap-2 border-y border-y-blue-400 dark:border-y-blue-500">
      <div className="py-1">
        <Button
          color="primary"
          variant="light"
          as={Link}
          to="/random"
          className="w-full text-base"
          startContent={<HILightBulb />}
        >
          Random Quote
        </Button>
      </div>
      <div className="py-1">
        <Button
          color="primary"
          variant="light"
          as={Link}
          to="/popular"
          className="w-full text-base"
          startContent={<HIStar />}
        >
          Popular Quote
        </Button>
      </div>
      <div className="py-1">
        <Button
          color="primary"
          variant="light"
          as={Link}
          to="/new"
          className="w-full text-base"
          startContent={<HIPencilSquare />}
        >
          Write Your Own
        </Button>
      </div>
    </div>
  </div>
)}
