// build-vue/src/components/QuoteRenderer.vue
<script setup lang="ts">
  import { ref, watch } from "vue"
import type { apiQuoteType } from "../utils/types";
import { API_HOST, HOST } from "../utils/config";

  const props = defineProps<{
    quote: apiQuoteType | null
  }>()

  const likeToggle = ref(false)
  const likeSuccess = ref(false)
  const shareToggle = ref(false)
  const shareLink = ref("")
  
  const newQuoteState = () => {
    if (props.quote != null) {
      likeToggle.value = false
      likeSuccess.value = false
      shareToggle.value = false
      shareLink.value = `${HOST}/id/${props.quote.id}`
    }
  }

  const likeQuote = async () => {
    likeToggle.value = true;
    const reqObj = {
      id: props.quote?.id
    }
    try {
      const res = await fetch(`${API_HOST}/like`, {
        method: 'POST', 
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(reqObj),
      });
      if (res.ok) {
        likeSuccess.value = true
      } else {
        likeToggle.value = false
      }
    } catch {
      likeToggle.value = false
    }
  }

  watch(props, newQuoteState)
</script>

<template>
  <div id="placeholder" v-if="quote === null">
    <p>Loading quote...</p>
  </div>
  <div v-else>
    <p id="quote">{{quote.quote}}</p>
    <p id="name">- {{quote.name}}</p>
    <div id="actions">
      <div class="button-container">
        <button 
          :disabled="likeToggle" 
          @click="likeQuote"
        >
          {{likeSuccess ? "Liked" : "Like"}} this quote
        </button>
      </div>
      <div class="button-container">
        <button 
          :disabled="shareToggle" 
          @click="() => {shareToggle = true}"
        >
          Share this quote
        </button>
      </div>
    </div>
    <div id="share-link" v-if="shareToggle">
      <p>Copy this link to share:</p>
      <input type="text" :value="shareLink" disabled>
    </div>
  </div>
</template>

<style scoped>
  .button-container {
    text-align: center;
  }
  p {
    font-family: "Open Sans", sans-serif;
  }
  #placeholder p {
  text-align: center;
  font-size: 24px;
  font-weight: bold;
  }
  #quote {
    text-align: justify;
    text-indent: 2em;
  }
  #name {
    text-align: right;
    font-style: italic;
  }
  #actions {
    display: grid;
    grid-template-columns: auto auto;
  }
  #share-link {
    align-items: center;
  }
  #share-link p {
    margin-bottom: 0px;
  }
  #share-link input {
    width: 354px;
    padding:2px;
    border-width:1px;
    font-family: "Open Sans", sans-serif;
    font-size: 16px;
  }
</style>

// build-react/src/components/QuoteRenderer.tsx
import styled from "styled-components"

import { useEffect, useState } from "react"
import { apiQuoteType } from "../utils/types"
import { API_HOST, HOST } from "../utils/config"

const Placeholder = styled.p`
  font-family: "Open Sans", sans-serif;
  font-size: 24px;
  font-weight: bold;
  text-align: center;
  margin: 0px;
`
const QuoteBody = styled.p`
  font-family: "Open Sans", sans-serif;
  text-align: justify;
  text-indent: 2em;
`
const QuoteName = styled.p`
  font-family: "Open Sans", sans-serif;
  text-align: right;
  font-style: italic;
`
const QuoteActions = styled.div`
  display: grid;
  grid-template-columns: auto auto;
`
const ShareHeader = styled.p`
  font-family: "Open Sans", sans-serif;
  margin-bottom: 0px;
`
const ShareLinkBox = styled.input`
  width: 354px;
  padding:2px;
  border-width:1px;
  font-family: "Open Sans", sans-serif;
  font-size: 16px;
`

type propsType = {
  quote: apiQuoteType | null
}

export default function QuoteRenderer (props: propsType) {
  const [likeToggle, likeToggleUpdate] = useState(false)
  const [likeSuccess, likeSuccessUpdate] = useState(false)
  const [shareToggle, shareToggleUpdate] = useState(false)
  const [shareLink, shareLinkUpdate] = useState("")

  const newQuoteState = () => {
    likeToggleUpdate(false)
    likeSuccessUpdate(false)
    shareToggleUpdate(false)
    if (props.quote != null) {
      shareLinkUpdate(`${HOST}/id/${props.quote.id}`)
    }
  }
  
  const likeQuote = async () => {
    if (!props.quote) {
      return
    }

    likeToggleUpdate(true)
    const reqObj = {
      id: props.quote.id
    }
    let res;
    try {
      res = await fetch(`${API_HOST}/like`, {
        method: 'POST', 
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(reqObj),
      });
      if (res.ok) {
        likeSuccessUpdate(true)
      } else {
        likeToggleUpdate(false)
      }
    } catch {
      likeToggleUpdate(false)
    }
  }

  useEffect(newQuoteState, [props.quote])

  if (props.quote == null) {
    return <Placeholder>Loading quote...</Placeholder>
  } else { 
    return (
      <div>
        <QuoteBody>{props.quote.quote}</QuoteBody>
        <QuoteName>- {props.quote.name}</QuoteName>
        <QuoteActions>
          <div className="button-container">
            <button 
              disabled={likeToggle} 
              onClick={likeQuote}
            >
              {likeSuccess ? "Liked" : "Like"} this quote
            </button>
          </div>
          <div className="button-container">
            <button 
              disabled={shareToggle} 
              onClick={() => {shareToggleUpdate(true)}}
            >
              Share this quote
            </button>
          </div>
        </QuoteActions>
        {shareToggle && (<div>
          <ShareHeader>Copy this link to share:</ShareHeader>
          <ShareLinkBox type="text" value={shareLink} disabled />
        </div>)}
      </div>
    )
  }
}
